apiVersion: v1
kind: Service
metadata:
  name: ordering-api-service
spec:
  ports:
  - name: ordering-api-service
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ordering-api