apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  labels:
    app: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api
        image: asia.gcr.io/gke-with-github/orderingapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
