apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ordering-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api
        image: amul047/orderingapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000