apiVersion: v1
kind: Service
metadata:
  name: ordering-api-service
spec:
  type: LoadBalancer
  ports:
  - name: ordering-api-service
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ordering-api